spring:
  profiles:
    active: stg

---
spring:
  profiles: stg
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://daapiqadb8001:3306/msapi?autoReconnect=true&useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: operator
    password: msapi
